name: nicolasmejia
favicon: null
layout_spectrum: 0.017438569338992238
typography_spectrum: 0.6098277987912297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.20012767100706697
  lightness: 0.9448630600236356
  saturation: 0.38639789656735957
  rhythmicContrast: 0.6410444320645183
purpose: []
